---

- hosts: all
  become: true
  tasks:

#Plays for all hosts

  - name: Install updates (Rocky)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Install updates (Rocky)
    apt:
      update_cache: dist
    when: ansible_distribution == "Ubuntu"

#Plays for web servers

  - hosts: web_servers
    become: true
   tasks: 

  - name: Install Apache, PHP support and Htop
    tags: apache,apache2,web_server,ubuntu
    apt:
     name:
      - apache2
      - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache, PHP support and Htop
    tags: apache,httpd,web_server,rocky
    dnf:
   name:
    - httpd
    - php
    state: latest
    when: ansible_distribution == "Rocky"

#plays for db servers

  - hosts: db_servers
    become: true
    tasks:

  - name: Install MariaDB (Rocky)
    tags: db,mariadb,rocky
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Install MariaDB (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

# Plays for file servers

  - hosts: db_servers
    become: true
    tasks:

  - name: Install Samba
    package:
      name: samba
      state: latest

  - name: Install nfs (Rocky)
    tags: file_server,nfs,rocky
    dnf:
      name: nfs-utils
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Install nfs (Ubuntu)
    tags: nfs,ubuntu,file_server
    apt:
      name: nfs-kernel-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for sites
    tags: apache,apache2,httpd
    copy:
      src: default_site,html
      dest: /var/www/html/index.html
