---

#Plays for all hosts

- hosts: all
  become: true
  tasks:

  - name: Install updates (Rocky)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Install updates (Rocky)
    apt:
      update_cache: dist
    when: ansible_distribution == "Ubuntu"

  - name: Create oga user
    tags: always
    user:
      name: oga
      group: root

  - name: Add ss key for oga
    tags: always
    authorized_key:
      user: oga
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH/Bpd4QIIbrJzrl2OJ1JCILdxvrBQUBSWDdE5R1nG8o  user key"

  - name: Add a sudoers file for oga
    tags: always
    copy:
        src: sudoer_oga
      dest: /etc/sudoers.d/oga
      owner: root
      group: root
      mode: 0440 

#Plays for web servers

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache, PHP support and Htop
    tags: apache,apache2,web_server,ubuntu
    apt:
     name:
      - apache2
      - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache, PHP support and Htop
    tags: apache,httpd,web_server,rocky
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: copy default html file for sites
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: start httpd (Rocky)
    tags: apache,httpd,rocky
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky"

  - name: Change email address for admin (Rocky)
    tags: apache,httpd,rocky
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin addyadedoyin@gmail.com
    when: ansibe_distribution == "Rocky"
    register: httpd

  - name: Restart httpd
    tags: apache,rocky,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

#plays for db servers

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB (Rocky)
    tags: db,mariadb,rocky
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Install MariaDB (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

# Plays for file servers

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba
    package:
      name: samba
      state: latest

  - name: Install Unzip
    package:
    name: unzip

  - name: Install OpenTofu
    unarchive:
      src: https://github.com/opentofu/opentofu/releases/download/v1.6.0-rc1/tofu_1.6.0-rc1_darwin_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


  - name: Install nfs (Rocky)
    tags: file_server,nfs,rocky
    dnf:
      name: nfs-utils
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Install nfs (Ubuntu)
    tags: nfs,ubuntu,file_server
    apt:
      name: nfs-kernel-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy manual html file for sites
    tags: apache,apache2,httpd
    copy:
      src: instruction_manual.txt
      dest: /home/yomi
      owner: root
      group: root
      mode: 0644
